### ISSUE TITLE
Received Register

### ISSUE THREAD

**Issue by ng-marcus** [nittygritty-uk/Atvero-Issues#418]
On dev ATVDEMO Received Register just shows "Loading"

Also, I've made uploads on other sides, e.g. live ATVDEMO, but they don't appear in the received register.

**Comment by jim80** [comment]
https://github.com/nittygritty-uk/Atvero-Issues/issues/406

??

**Comment by LBoyle** [comment]
JH That would be useful, but it's not a solution to this problem, 406 should be a separate issue. 

When you see "Loading..." it will mean there are no items to load. 

Currently I don't enforce that ATVTransmittal and ATVReceivedOn are always set, if they're not, you get a broken table. 

I haven't chased down every spot where we'll need to set or update the new values, in fact, I said so several times.

**Comment by LBoyle** [comment]
Fixed in https://github.com/nittygritty-uk/Atvero/pull/422

**Comment by LBoyle** [comment]
Cursory testing, it's possible that I'll set receivedOn for non-received files, but I don't think that'll cause any problems, it's just like date created.

**Comment by allanchaplin** [comment]
On ATVDEMO I still get 'loading' on the received register.  If there are no received files (with transmittal ids) can it indicate that is the case

**Comment by jim80** [comment]
That was Issue #406 Allan, which I've now dealt with.
